### PR TITLE
indicate read-only state in icon color

### PR DESCRIPTION
**Pull request by rabauke**
Just a minor change to indicate the read-only state by the icon color. I also changed the icon from the keyboard icon to the pen icon, which I find more appropriate. But this might be a matter of taste. The keyboard icon is very schematic and the keyboard might not be recognized as a keyboard immediately.

### CODE REVIEW

**Comment by GoAlexander** [comment]
[Test pull request](https://trello.com/c/MQI4P0j9/39-test-pull-request)

**Comment by GoAlexander** [comment]
I did not understand for what is  `inputMethodHints: Qt.ImhNoAutoUppercase` ?

**Comment by GoAlexander** [comment]
In the past I tested design with `edit` icon - I don`t like it but different icon color is good idea!

**Comment by rabauke** [comment]
The `inputMethodHints: Qt.ImhNoAutoUppercase` prevents to automatically upcase the first letter in the search field. See [QT documentation](http://doc.qt.io/qt-5/qml-qtquick-controls-textfield.html#inputMethodHints-prop). I reverted the change of the read-only icon in the menu. Heiko

**Comment by GoAlexander** [comment]
Thanks for the explanation.  
The last one question before merging: 
I think it is mistake with the question mark in your code `"image://theme/icon-m-keyboard?"`  
I think it should be like `"image://theme/icon-m-keyboard"`
i ask it because you wrote it twice

**Comment by rabauke** [comment]
No, the question mark is not a mistake according to the [Sailfish OS documentation](https://sailfishos.org/develop/docs/jolla-ambient/).

**Comment by GoAlexander** [comment]
Oh, sorry forgot about this `Silica supports colorizaton of monochrome icons with "?" + color notation.`
Thanks for contribution!

**Pull request merged**
