### PR TITLE
Update harbour-editor-sv.ts

### PR DESCRIPTION
**Pull request by eson57**

### CODE REVIEW

**Comment by GoAlexander** [comment]
What happened? )

**Comment by eson57** [comment]
Don't know! I had some error message that I couldn't handle. I'm restoring branch to see if you can use the file.  ;)

**Comment by GoAlexander** [comment]
I fixed conflicts and added missed `-` :)

**Comment by eson57** [comment]
Thanks! I couldn't find how to do that.  :)

**Comment by GoAlexander** [comment]
I did not hear feedback long time. So I want to ask you some question which are important for the next development rounds:
Do you use Editor often? What do you like? What don`t you like? What features do you need first of all?

P.S.
 I think will appear in December: history of opened documents, undo/redo, initial search, maybe some new small features like inserting date/fast deleting

**Comment by eson57** [comment]
Well, I'm hardly leaving office these days, so I don't use my phone for pretty much anything but talking. I find my desktop system a lot easier to work with. ;)
Undo/redo and search will of course become handy, the few times I'm out of house and need to do something urgent.

**Pull request merged**
