### PR TITLE
Update harbour-editor-es.ts

### PR DESCRIPTION
**Pull request by Caballlero**
HELP WANTED ABOUT WHAT IS Highlighting ?

### CODE REVIEW

**Comment by GoAlexander** [comment]
"Highlighting" means for the syntax highlighting

See the text: https://www.dropbox.com/s/mynf0mpocufzpzd/photo_2017-05-01_12-44-17.jpg?dl=0

**Comment by GoAlexander** [comment]
Can I merge it?

**Comment by Caballlero** [comment]
merge

**Comment by GoAlexander** [comment]
Ok, thanks for the contribution. I hope you will like new version.

**Comment by Caballlero** [comment]
when the new release v.0.7 ??? i am waiting.................................

**Comment by GoAlexander** [comment]
I hope that in this month but I am very busy for now (course work and so on) so I can not promise.  
If it is interesting for you current changelog is here: https://github.com/GoAlexander/harbour-editor/issues/19
  
To release new update we have to:
- add some fixes for code highlighting
- (maybe) implement sending to of document to the Dropbox

**Comment by Caballlero** [comment]
- Many interesting things EDITOR V.0.7 thanks

**Pull request merged**
