### PR TITLE
Update harbour-editor-sv.ts

### PR DESCRIPTION
**Pull request by eson57**

### CODE REVIEW

**Comment by Caballlero** [comment]
Hello eson:  I think I saw a  mistake by CASUALLY, check line 140 the words   "grupp" to "gruppe"  ...?

**Comment by eson57** [comment]
No, grupp is correct Swedish. "Gruppe" is German. 😉

**Comment by Caballlero** [comment]
ok.

**Comment by GoAlexander** [comment]
Thank you for your continuous  support of the app!

**Pull request merged**
