### PR TITLE
Update harbour-editor-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Line 63/64 still don't translate.

### CODE REVIEW

**Comment by GoAlexander** [comment]
Will try to update .ts file. In the next version will see if something changed...

**Comment by GoAlexander** [comment]
I published version 0.3 of app. Is bug fixed?

**Comment by eson57** [comment]
Sorry, not fixed by updating from Warehouse.

skarmbild_20161130_001

**Comment by GoAlexander** [comment]
But in the past there were two lines. Yes?

**Comment by eson57** [comment]
Yes, the donation line was fixed by my first ts file edit. The one in harbour-exporter. It never showed up in Editor.

**Pull request merged**
