### PR TITLE
Update French file

### PR DESCRIPTION
**Pull request by Quenty31**
Should be okay now :)

### CODE REVIEW

**Comment by Quenty31** [comment]
What should I do?

**Comment by GoAlexander** [comment]
I should upload new translation files. After that you can edit them.  
When will I upload? I will try as soon as possible... Now busy with another tasks...
  
Any way thanks for the contribution! :)

**Comment by GoAlexander** [comment]
Thanks for the contribution. Finally I pushed new translations. Please re-create Pull Request.

**Comment by GoAlexander** [comment]
Not relevant now

**Pull request closed without merging**
