### PR TITLE
Update harbour-editor-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Can I ask why don't you also update Swedish ts file with new/changed strings?

### CODE REVIEW

**Comment by GoAlexander** [comment]
What do you mean?

**Comment by eson57** [comment]
No, so far not in sv.ts. Only in the other two files.

**Comment by GoAlexander** [comment]
Why I didn't translate de and original ts file? Do you ask that?

**Comment by GoAlexander** [comment]
If yes I don't need these files now. I have another priorities

**Comment by eson57** [comment]
No, it's not about translation. When you update source ts file with new/changed strings, you should also update sv.ts with the same new/changed strings. That way it is easy for me to just translate the new strings. 
As for now, I have to first find and merge the new/changed strings into my file and then translate.

**Comment by GoAlexander** [comment]
Hm, thanks. I didn't mention it. In my past experience in development for Sailfish OS updating working automatically... I will check the settings... It should working... Thank for the explanation I didn't know about this problem.

P.S. I think soon I will publish it on transifex.

**Comment by eson57** [comment]
Great! Transifex is good. I'm sure you will have more translations there.  :+1:

**Comment by GoAlexander** [comment]
I think I fixed bug: 14c894a0984b9daea6e558c01cffe68e570e975d  
It should auto generate each time. Next time send me issues if you see something brokean :)

**Comment by eson57** [comment]
Thanks! I will.  :)

**Pull request merged**
