### PR TITLE
SPANISH

### PR DESCRIPTION
**Pull request by Caballlero**

### CODE REVIEW

**Comment by GoAlexander** [comment]
Fix next lines and I will merge it:  
13 -> to `<translation>No archivos</translation>`
20 -> "Editor" repeated twice. Fix to: `<translation>&quot;Editor.&quot; de texto rico en funciones!</translation>`
24 -> I think it can be `<translation>Licensia: GPLv3</translation>` but as you wish...
44 -> to `<translation>Acerca de</translation>` (without ":")
52 - > I think you forgot to delete "To" in the beginning and translate "Select all text" <translation>-To &apos;Select all text&apos; Sostenga su dedo hasta 3 vibraciones</translation>
56 - > "osanwe" NOT "osawe"
64 - > Should begin with capital letter
148 -> Should begin with capital letter
157 -> Better delete ":"
161 -> Should begin with capital letter

Buttons translated excellent! :)

P.S.  
&apos; is " in the app

**Comment by Caballlero** [comment]
All the lines are fixed, line 52 I NOT SURE IT IS OK  > CHECK PLEASE <

**Comment by GoAlexander** [comment]
Syntax is ok. Merged. Thanks for the contribution!

**Comment by GoAlexander** [comment]
I want to mention all translators in AboutPage. Which nickname should I use by you? Caballlero?

**Comment by GoAlexander** [comment]
And answer on my question about Editor. which I asked you by email :) These question are important for me :)

**Pull request merged**
