### PR TITLE
Remove dot from app name in *.desktop

### PR DESCRIPTION
**Pull request by Self-Perfection**
App name with dot at the end looks weird and unjustified. No other app from installed on my SfOS device have dot in launch icon.

### CODE REVIEW

**Comment by GoAlexander** [comment]
That was special. If you see all my apps have dots. Something like "design feature".  
I am on the edge of rethinking of my app (new UI and so on) so I need to think and maybe in the future I will merge it.

**Comment by GoAlexander** [comment]
Anyway thank you for the contribution.

**Comment by Self-Perfection** [comment]
My bad. I was definitely sure, that this dot is a typo. I should have checked more thoroughly before proposing this PR.

**Comment by GoAlexander** [comment]
Everything is fine. Anyway in some month (when I will have free time) I will make big redesign of app that I discussed with the community in telegram. I will review your pull request again.

**Comment by GoAlexander** [comment]
Thanks for the active position :) Feedback is always welcome.

**Pull request closed without merging**
